### ISSUE TITLE
Expect on HPACK tables

### ISSUE THREAD

**Issue by Dridi** [gquintard/h2vtcspec#1]
From the current syntax:

```
expect outtable[4].key == "x-cache"
expect intable[1].value == "307"
```

First suggestion is to name the tables `tbl.enc`(encoding table) and `tbl.dec` (decoding table). The second suggestion is to treat the table as a multi-line string for comparison, comparing only non-blank lines, with a way to ignore entries for instance:

```
# a star means that we ignore a key or value, inspired by logexpect
expect tbl.dec ~ {
    * *
    * *
    * *
    x-cache *
}

expect tbl.enc ~ {
    * 307 
}
```

**Comment by gquintard** [comment]
No problem on my side for tbl.enc/dec.

the other proposal on the other hand would need a new keywork as expect doesn't work like that.

**Comment by Dridi** [comment]
> the other proposal on the other hand would need a new keywork as expect doesn't work like that.

I don't understand, like what?

**Comment by gquintard** [comment]
expect LHS CMP RHS;

**Comment by Dridi** [comment]
> expect LHS CMP RHS; So the proposed syntax won't work, but we can pick a new keyword to do it.

From my example:

- `LHS`: `tbl.dec`
- `CMP`: `~` (we could use a different token)
- `RHS`: `"\n\t* *\n\t* *\n\t* *\n\tx-cache *\n"`

The curly braces only represent multi-line character strings in varnishtest, so it can be used on an expect command line. It's just a token that happens to span multiple lines, it still belongs to the `expect` command line.

And IIRC there's no `;` at the end of an expect.

**Comment by gquintard** [comment]
'~' won't work since it's for regex matching, so yes, other token or other keyword, which amount to pretty much the same amount of work :-)

**Comment by gquintard** [comment]
``tbl.enc`` and ``tbl.dec`` are now commited.
